Repository BurdaMagazinOrg/theme-thunder-admin, pull requests merged in 2020-04, with the labels that each got.

#297 Update reference images (metatag update)
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  screenshots/reference/admin_content_media-media-chrome_1280.png
  screenshots/reference/admin_content_media-media-firefox_1280.png
  screenshots/reference/admin_modules-chrome_1280.png
  screenshots/reference/admin_modules-firefox_1280.png
  screenshots/reference/admin_structure-admin_structure-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-article_display-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-article_display-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-cleanup_details_element_as_field_group-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-cleanup_details_element_as_field_group-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-configure_details_element_as_field_group-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-configure_details_element_as_field_group-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-show_description_on_form_error-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-show_description_on_form_error-firefox_1280.png
  screenshots/reference/node_7_edit-ckeditor_dialog-chrome_1280.png
  screenshots/reference/node_7_edit-ckeditor_dialog-firefox_1280.png
  screenshots/reference/node_7_edit-entity_browser_gallery-chrome_1280.png
  screenshots/reference/node_7_edit-entity_browser_gallery-firefox_1280.png
  screenshots/reference/node_7_edit-paragraphs_modified_content_message-chrome_1280.png
  screenshots/reference/node_7_edit-paragraphs_modified_content_message-firefox_1280.png
  screenshots/reference/node_7_edit-select2_dropdown-chrome_1280.png
  screenshots/reference/node_add_article-linkit_dialog-chrome_1280.png
  screenshots/reference/node_add_article-linkit_dialog-firefox_1280.png
  screenshots/reference/node_add_article-modals_in_paragraphs-chrome_1280.png
  screenshots/reference/node_add_article-modals_in_paragraphs-firefox_1280.png
  sharpeye.conf.js
  sharpeye.tasks.js
Labels: 2.x

#290 thunder-admin-tests updates
  .github/workflows/test.yml
  package-lock.json
  package.json
  screenshots/reference/admin_modules-chrome_1280.png
  screenshots/reference/admin_modules-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-article_display-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-article_display-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-cleanup_details_element_as_field_group-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-cleanup_details_element_as_field_group-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-configure_details_element_as_field_group-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-configure_details_element_as_field_group-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-show_description_on_form_error-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_form-display-show_description_on_form_error-firefox_1280.png
  screenshots/reference/node_7_edit-select2_dropdown-chrome_1280.png
  sharpeye.conf.js
  sharpeye.tasks.js
Labels: 3.x

#299 Update npm packages
  package-lock.json
  package.json
  screenshots/reference/node_7_edit-select2_dropdown-chrome_1280.png
Labels: 3.x

#300 Update npm packages
  package-lock.json
  package.json
  screenshots/reference/admin_structure_types_manage_article_display-open_tabs-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-open_tabs-firefox_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-resize_tabs-chrome_1280.png
  screenshots/reference/admin_structure_types_manage_article_display-resize_tabs-firefox_1280.png
  sharpeye.tasks.js
Labels: 2.x

#294 Entity browser update
  css/components/media-form.css
  sass/components/media-form.scss
  screenshots/reference/node_add_article-modals_in_paragraphs-firefox_1280.png
  screenshots/reference/node_add_article-paragraphs-chrome_1280.png
  screenshots/reference/node_add_article-paragraphs-firefox_1280.png
Labels: do not merge
